services:
  application:
    container_name: application-development
    env_file:
      - .env.dev
    build:
      target: Development
    ports:
      - "3002:3000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./internal:/app/internal
#      - ./pkg:/app/pkg
      - ./.air.toml:/app/.air.toml
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
  application-debug:
    container_name: application-development-debug
    env_file:
      - .env.dev
    build:
      target: Development
    ports:
      - "3003:3000"
      - "2345:2345"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./internal:/app/internal
#      - ./pkg:/app/pkg
      - ./.air.debug.toml:/app/.air.toml
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum

  application-proto:
    container_name: application-proto
    command: sh -c "protoc grpc/*.proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --proto_path=."
    build:
      target: protobuf-grpc-build
    volumes:
      - ./internal/grpc:/app/grpc
